# Generated by Django 4.2.7 on 2026-04-29 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("professional", "Professional Elective"),
                            ("open", "Open Elective"),
                            ("ability", "Ability Enhancement"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "salient_features",
                    models.TextField(help_text="Key highlights and topics covered"),
                ),
                (
                    "job_perspective",
                    models.TextField(
                        help_text="Career opportunities this course opens"
                    ),
                ),
                (
                    "prerequisites",
                    models.TextField(
                        blank=True, help_text="Required prior knowledge/courses"
                    ),
                ),
                ("total_seats", models.PositiveIntegerField(default=30)),
                ("available_seats", models.PositiveIntegerField(default=30)),
                (
                    "semester_offered",
                    models.PositiveIntegerField(
                        default=5, help_text="Which semester this is offered"
                    ),
                ),
                (
                    "branch_quota",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Branch-wise seat limits. E.g. {"CSE": 10, "ECE": 5}',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_number", models.CharField(max_length=20, unique=True)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("CSE", "Computer Science"),
                            ("ECE", "Electronics & Communication"),
                            ("MECH", "Mechanical Engineering"),
                            ("CIVIL", "Civil Engineering"),
                            ("EEE", "Electrical Engineering"),
                            ("IT", "Information Technology"),
                            ("CHEM", "Chemical Engineering"),
                            ("BIO", "Biotechnology"),
                        ],
                        max_length=10,
                    ),
                ),
                ("current_semester", models.PositiveIntegerField(default=1)),
                (
                    "cgpa",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                ("phone", models.CharField(blank=True, max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField(help_text="1 = top choice")),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("allocated", "Allocated"),
                            ("waitlisted", "Waitlisted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "waitlist_position",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="electives.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="electives.student",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp", "rank"],
                "unique_together": {("student", "course")},
            },
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="electives.department",
            ),
        ),
        migrations.CreateModel(
            name="StudentCourseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester_completed", models.PositiveIntegerField()),
                ("grade", models.CharField(blank=True, max_length=5)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electives.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="electives.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "course")},
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocated_at", models.DateTimeField(auto_now_add=True)),
                ("is_admin_override", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="electives.course",
                    ),
                ),
                (
                    "preference",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation",
                        to="electives.preference",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="electives.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "course")},
            },
        ),
    ]
